# .github/workflows/scheduled-builds.yml
name: EcoData

on:
  # schedule:
    # (see https://crontab.guru) UTC Time
    # - cron: "0 * * * *"
  
  workflow_dispatch:

jobs:
  build:
    name: Refresh data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed

      - name: Run PVPC script
        uses: borales/actions-yarn@v4
        with:
          cmd: pvpc

      - name: Add and commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          message: "Update PVPC"
